import sharp from "sharp";
import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = join(__dirname, "..");
const inputPath = join(root, "public/portrait.png");
const outputPath = join(root, "src/data/portrait.ts");

// Dense glyphs for darker areas (reads well on dark terminal bg)
const RAMP = "@%#*+=-:. ";

const WIDTH = 56;
const HEIGHT = 56;
const BG_LUMA_MAX = 28; // near-black backdrop → space

function luminance(r, g, b) {
  return 0.299 * r + 0.587 * g + 0.114 * b;
}

function trimAscii(lines) {
  if (lines.length === 0) return lines;

  let top = lines.length;
  let bottom = -1;
  let left = Infinity;
  let right = -1;

  for (let y = 0; y < lines.length; y++) {
    for (let x = 0; x < lines[y].length; x++) {
      if (lines[y][x] !== " ") {
        top = Math.min(top, y);
        bottom = Math.max(bottom, y);
        left = Math.min(left, x);
        right = Math.max(right, x);
      }
    }
  }

  if (bottom < 0 || left === Infinity) return lines;

  return lines.slice(top, bottom + 1).map((line) => line.slice(left, right + 1));
}

async function generate() {
  const { data, info } = await sharp(inputPath)
    .resize(WIDTH, HEIGHT, { fit: "cover", position: "centre" })
    .ensureAlpha()
    .raw()
    .toBuffer({ resolveWithObject: true });

  const channels = info.channels;
  const lines = [];

  // Collect subject luminances for contrast stretch
  const subjectLumas = [];
  for (let i = 0; i < data.length; i += channels) {
    const lum = luminance(data[i], data[i + 1], data[i + 2]);
    if (lum > BG_LUMA_MAX) subjectLumas.push(lum);
  }

  subjectLumas.sort((a, b) => a - b);
  const p5 = subjectLumas[Math.floor(subjectLumas.length * 0.05)] ?? 0;
  const p95 = subjectLumas[Math.floor(subjectLumas.length * 0.95)] ?? 255;
  const range = Math.max(1, p95 - p5);

  for (let y = 0; y < HEIGHT; y++) {
    let line = "";
    for (let x = 0; x < WIDTH; x++) {
      const idx = (y * WIDTH + x) * channels;
      const lum = luminance(data[idx], data[idx + 1], data[idx + 2]);

      if (lum <= BG_LUMA_MAX) {
        line += " ";
        continue;
      }

      // Stretch contrast across subject; invert so dark → dense
      const normalized = Math.min(1, Math.max(0, (lum - p5) / range));
      const charIdx = Math.min(
        RAMP.length - 1,
        Math.floor((1 - normalized) * (RAMP.length - 1)),
      );
      line += RAMP[charIdx];
    }
    lines.push(line);
  }

  const trimmed = trimAscii(lines);
  const ascii = trimmed.join("\n");
  const content = `// Generated by scripts/generate-ascii.mjs — do not edit manually
export const portraitAscii = ${JSON.stringify(ascii)};
`;

  writeFileSync(outputPath, content, "utf8");
  console.log(`Wrote ${outputPath} (${trimmed[0]?.length ?? 0}x${trimmed.length})`);
}

generate().catch((err) => {
  console.error(err);
  process.exit(1);
});
