// Generated by scripts/fetch-github-stats.mjs — do not edit by hand.
// Re-run: npm run fetch:github-stats

export const githubStats = [
  {
    "label": "Repos",
    "value": "67"
  },
  {
    "label": "Commits",
    "value": "810"
  },
  {
    "label": "LOC",
    "value": "",
    "html": true,
    "additions": "120,567++",
    "deletions": "2,320--"
  },
  {
    "label": "Stars",
    "value": "5"
  },
  {
    "label": "Followers",
    "value": "2"
  }
] as const;
